services:
    emag.core.compte.solde_updater:
        class:  CoreBundle\Service\Compte\SoldeUpdater
        lazy:   true
        sharde: true
    emag.core.compte.ticket_updater:
        class:  CoreBundle\Service\Compte\TicketUpdater
        lazy:   true
        sharde: true
    emag.core.compte.ticket_renouvellement:
        class:  CoreBundle\Service\Compte\TicketRenouvellement
        lazy:   true
        shared: true
        arguments: ["@emag.core.compte.ticket_updater"]