services:
    emag.core.type_compte:
        class:  CoreBundle\Service\Compte\TypeCompteService
        lazy:   true
        shared: true

    emag.core.ajustement:
        class:  CoreBundle\Service\Operation\AjustementService
        lazy:   true
        shared: true

    emag.core.renouvellement:
        class:  CoreBundle\Service\Operation\RenouvellementService
        lazy:   true
        shared: true

    emag.core.compte:
        class:  CoreBundle\Service\Compte\CompteService
        lazy:   true
        shared: true

    emag.core.compte.ticket:
        class:  CoreBundle\Service\Compte\CompteTicketService
        lazy:   true
        shared: true

    emag.core.mode_paiement:
        class:  CoreBundle\Service\ModePaiement\ModePaiementService
        lazy:   true
        shared: true

    emag.core.abstract.operation:
        class:    CoreBundle\Service\Operation\AbstractOperationService
        lazy:     true
        shared:   true
        abstract: true
        arguments:
            - "@emag.core.compte"
            - "@emag.core.type_compte"

    emag.core.operation.tranfert_argent:
        class:  CoreBundle\Service\Operation\TransfertArgentService
        parent: emag.core.abstract.operation
        shared: true

    emag.core.operation.ticket:
        class:  CoreBundle\Service\Operation\OperationTicketService
        parent: emag.core.abstract.operation
        shared: true
        arguments:
            - "@emag.core.compte.ticket"

    emag.core.operation:
        class:  CoreBundle\Service\Operation\OperationService
        parent: emag.core.abstract.operation
        shared: true
        arguments:
            - "@emag.core.mode_paiement"
            - "@emag.core.operation.ticket"

    emag.core.mise_a_jour_solde:
        class:  CoreBundle\Service\MiseAJourSolde
        lazy:   true
        shared: true
        arguments:
            - "@emag.core.compte"
            - "@emag.core.ajustement"
            - "@emag.core.renouvellement"