fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

emag_user:
    resource: "@EmagUserBundle/Controller/LoginController.php"
    type:     annotation
    prefix:   /test