<?php

namespace CoreBundle\Repository;

/**
 * AjustementSoldeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AjustementSoldeRepository extends \Doctrine\ORM\EntityRepository
{
}
