<?php

namespace CoreBundle\Repository;

/**
 * AutreCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutreCompteRepository extends \Doctrine\ORM\EntityRepository
{
}
