<?php

namespace CoreBundle\Repository;

/**
 * ChequierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChequierRepository extends \Doctrine\ORM\EntityRepository
{
}
