<?php

namespace CoreBundle\Repository;

/**
 * CompteSoldeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteSoldeRepository extends \Doctrine\ORM\EntityRepository
{
}
