<?php

namespace CoreBundle\Repository;

/**
 * CompteChequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteChequeRepository extends \Doctrine\ORM\EntityRepository
{
}
