<?php

namespace CoreBundle\Repository;

/**
 * CompteTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
