<?php

namespace CoreBundle\Repository;

/**
 * OperationTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
