<?php

namespace CoreBundle\Repository;

/**
 * OperationChequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationChequeRepository extends \Doctrine\ORM\EntityRepository
{
}
