<?php

namespace CoreBundle\Repository;

/**
 * OperationEspecesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationEspecesRepository extends \Doctrine\ORM\EntityRepository
{
}
