<?php

namespace CoreBundle\Repository;

/**
 * OperationCouranteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationCouranteRepository extends \Doctrine\ORM\EntityRepository
{
}
