<?php

namespace CoreBundle\Repository;

/**
 * PaiementOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
