<?php

namespace CoreBundle\Repository;

/**
 * PorteMonnaieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PorteMonnaieRepository extends \Doctrine\ORM\EntityRepository
{
}
