<?php

namespace CoreBundle\Repository;

/**
 * PrelevementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrelevementRepository extends \Doctrine\ORM\EntityRepository
{
}
