<?php

namespace CoreBundle\Repository;

/**
 * RemiseChequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemiseChequeRepository extends \Doctrine\ORM\EntityRepository
{
}
