<?php

namespace CoreBundle\Repository;

/**
 * RenouvellementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RenouvellementRepository extends \Doctrine\ORM\EntityRepository
{
}
