<?php

namespace CoreBundle\Repository;

/**
 * TransfertArgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransfertArgentRepository extends \Doctrine\ORM\EntityRepository
{
}
