<?php

namespace CoreBundle\Repository;

/**
 * VirementExterneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VirementExterneRepository extends \Doctrine\ORM\EntityRepository
{
}
