<?php

namespace CoreBundle\Repository;

/**
 * VirementInterneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VirementInterneRepository extends \Doctrine\ORM\EntityRepository
{
}
