<?php

namespace CoreBundle\Repository;

/**
 * VirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VirementRepository extends \Doctrine\ORM\EntityRepository
{
}
