<?php

namespace EmagUserBundle\Repository;

/**
 * EmagUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmagUserRepository extends \Doctrine\ORM\EntityRepository
{
}
